/**
 * The monthly report's words, Hebrew and English. Kept beside the component
 * rather than in the shared dashboard dictionary so the feature is one
 * self-contained block. Written for this product; nothing is borrowed from
 * another tool's wording.
 */
import { intlLocaleOf, type PublicLocale } from '@/lib/i18n/locales'

const intlLocale = intlLocaleOf

export function monthName(key: string, l: PublicLocale): string {
  const [y, m] = key.split('-').map(Number)
  if (!y || !m) return key
  return new Intl.DateTimeFormat(intlLocale(l), { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(Date.UTC(y, m - 1, 1)))
}

export function monthOnly(key: string, l: PublicLocale): string {
  const [y, m] = key.split('-').map(Number)
  if (!y || !m) return key
  return new Intl.DateTimeFormat(intlLocale(l), { month: 'long', timeZone: 'UTC' }).format(new Date(Date.UTC(y, m - 1, 1)))
}

export function dayMonth(iso: string, l: PublicLocale): string {
  const t = Date.parse(iso.length === 10 ? `${iso}T00:00:00Z` : iso)
  if (!Number.isFinite(t)) return iso
  return new Intl.DateTimeFormat(intlLocale(l), { day: 'numeric', month: 'long', timeZone: 'UTC' }).format(new Date(t))
}

export function count(n: number, l: PublicLocale): string {
  return new Intl.NumberFormat(intlLocale(l), { maximumFractionDigits: 0 }).format(Math.round(n))
}

export function decimal(n: number, l: PublicLocale): string {
  return new Intl.NumberFormat(intlLocale(l), { maximumFractionDigits: 1 }).format(n)
}

const he = {
  title: 'דוחות חודשיים',
  subtitle: 'בכל 1 לחודש נוצר כאן סיכום של החודש שהסתיים: דירוגים, תוכן, נראות ב-AI ו-Search Console. אין מה להגדיר.',
  monthsLabel: 'חודשים',
  loading: 'טוען את הדוחות החודשיים…',
  loadError: 'לא הצלחנו לטעון את הדוחות החודשיים.',
  retry: 'לנסות שוב',
  firstTitle: (date: string) => `הדוח החודשי הראשון ייווצר ב-${date}`,
  firstBody: (month: string) => `הוא ייבנה מעצמו ויסכם את ${month}: אילו מילים טיפסו ואילו נסוגו, מה עלה לאוויר, איך מנועי ה-AI הזכירו אתכם ומה על הפרק בחודש שאחריו. עד אז הנתונים ממשיכים להיאסף.`,
  firstList: ['תנועת מילות המפתח ומספר המילים בעמוד הראשון', 'המאמרים שפורסמו', 'אזכורים וציטוטים במנועי AI', 'קליקים וחשיפות מ-Search Console, אם מחובר', 'מה מתוכנן לחודש הבא'],
  missingTitle: (month: string) => `הדוח של ${month} עוד לא נוצר`,
  missingBody: 'זה קורה בפרויקט שנפתח באמצע החודש או לפני שהדוחות החודשיים הופעלו. אפשר ליצור אותו עכשיו מהנתונים שכבר שמורים; אחרי שנוצר הוא לא משתנה.',
  missingAction: (month: string) => `ליצור את הדוח של ${month}`,
  insideTitle: 'מה ייכנס לכל דוח',
  insideBody: (date: string) => `מהחודש הבא אין צורך ללחוץ: הדוח הבא ייווצר מעצמו ב-${date}.`,
  missingFailed: 'לא הצלחנו ליצור את הדוח. נסו שוב בעוד רגע.',
  generateToast: { pending: 'יוצרים את הדוח מהנתונים השמורים. זה לוקח כמה שניות.', done: 'הדוח נוצר, והוא מוצג כאן.', failed: 'לא הצלחנו ליצור את הדוח. נסו שוב בעוד רגע.' },
  nextReport: (date: string) => `הדוח הבא: ${date}`,
  generatedAuto: (date: string) => `נוצר אוטומטית ב-${date}`,
  generatedOwner: (date: string) => `נוצר לבקשתכם ב-${date}`,
  coversFrom: (date: string) => `הפרויקט נפתח ב-${date}, ולכן הדוח מתחיל מאותו יום.`,
  copy: 'העתקת הסיכום',
  copied: 'הסיכום הועתק',
  download: 'הורדת הדוח',
  downloading: 'מכינים את הקובץ…',
  downloadFailed: 'לא הצלחנו להכין את הקובץ. נסו שוב בעוד רגע.',
  headlineParts: {
    firstPage: (n: string) => `${n} מילים בעמוד הראשון של גוגל`,
    improved: (n: string) => `${n} מילים טיפסו`,
    dropped: (n: string) => `${n} נסוגו`,
    published: (n: string) => `${n} מאמרים פורסמו`,
    clicks: (n: string) => `${n} קליקים מגוגל`,
    quiet: 'חודש שקט: לא נרשמה תנועה בדירוגים ולא פורסם תוכן.',
  },
  tiles: {
    firstPage: 'בעמוד הראשון',
    firstPageSource: 'מעקב הדירוג שלנו · מקומות 1-10',
    wasAtStart: (n: string) => `בתחילת החודש: ${n}`,
    improved: 'מילים שטיפסו',
    improvedSource: (steady: string) => `ללא שינוי: ${steady}`,
    published: 'מאמרים שפורסמו',
    publishedSource: 'וורדפרס ושופיפיי, דרך האפליקציה',
    clicks: 'קליקים מגוגל',
    clicksSource: (from: string, to: string) => `${from} עד ${to} · Search Console`,
    clicksMissing: 'אין נתון',
    noChecks: 'לא נבדק החודש',
    noKeywords: 'אין מילים במעקב',
  },
  improvedTitle: 'מה טיפס',
  droppedTitle: 'מה נסוג',
  movesSub: 'מהבדיקה שלפני החודש עד הבדיקה האחרונה בו',
  outside: 'מחוץ ל-100',
  mapsTag: 'מפות',
  more: (n: string) => `ועוד ${n}`,
  noKeywords: 'עוד אין מילות מפתח במעקב, אז אין תנועה להשוות. מילים שתוסיפו ייכנסו לדוח הבא.',
  noKeywordsAction: 'להוספת מילות מפתח',
  noChecks: 'המילים לא נבדקו החודש. כדי לראות תנועה צריך לפחות בדיקת דירוג אחת בחודש.',
  noChecksAction: 'לבדיקת הדירוגים',
  noneImproved: (steady: string) => `אף מילה לא טיפסה החודש. ${steady} נשארו באותו מקום.`,
  noneDropped: 'אף מילה לא נסוגה החודש.',
  singleCheck: 'רוב המילים נבדקו פעם אחת בלבד, ולכן אין עדיין נקודת השוואה. מהחודש הבא תופיע כאן התנועה שלהן.',
  publishedTitle: 'מה פורסם',
  publishedNone: (month: string) => `לא פורסמו מאמרים ב${month}. כל מאמר שיעלה דרך האפליקציה ייספר בחודש שבו פורסם.`,
  publishedAction: 'לאסטרטגיית התוכן',
  channel: { wordpress: 'וורדפרס', shopify: 'שופיפיי', other: 'פורסם' },
  aiTitle: 'נראות במנועי AI',
  aiNone: 'לא הורצו בדיקות נראות ב-AI בחודש הזה. בדיקה אחת מספיקה כדי שהדוח הבא יראה כמה פעמים הוזכרתם ומתי צוטטתם כמקור.',
  aiAction: 'לבדיקת נראות',
  aiAnswers: 'תשובות שנבדקו',
  aiMentions: 'הוזכרתם',
  aiCitations: 'צוטטתם כמקור',
  gscTitle: 'Search Console',
  gscNotConnected: 'הפרויקט לא מחובר ל-Search Console, ולכן אין כאן קליקים וחשיפות. מהחיבור והלאה הם ייכנסו לכל דוח.',
  gscConnect: 'לחיבור Search Console',
  gscNoData: 'הפרויקט מחובר ל-Search Console, אבל אין סנכרון שמכסה את החודש הזה. הסנכרון רץ פעם בשבוע, וגוגל מעדכנת את הנתונים באיחור של כיומיים.',
  gscClicks: 'קליקים',
  gscImpressions: 'חשיפות',
  gscWindow: (from: string, to: string) => `28 ימים, ${from} עד ${to}`,
  gscVsPrevious: (from: string, to: string) => `לעומת ${from} עד ${to}`,
  planTitle: (month: string) => `מה מתוכנן ל${month}`,
  planSub: 'כפי שהתוכנית נראתה ביום שבו הדוח נוצר',
  planScheduled: 'מתוזמנים לפרסום',
  planQueued: (n: string) => `${n} מאמרים ממתינים בתור הפרסום האוטומטי`,
  planReady: (n: string) => `${n} מאמרים כתובים ומחכים לפרסום`,
  planApproved: 'נושאים שאישרתם לכתיבה',
  planIdeas: 'רעיונות שהוצעו ומחכים להחלטה',
  planEmpty: 'אין עדיין תוכנית תוכן לחודש הבא. אסטרטגיית התוכן תציע נושאים לפי מילות המפתח שלכם, ומה שתאשרו יופיע כאן.',
  teaser: {
    title: 'הדוח החודשי',
    open: 'לדוח המלא',
    firstBody: (date: string) => `הדוח הראשון ייווצר ב-${date} ויסכם את החודש הנוכחי.`,
    missingBody: (month: string) => `הדוח של ${month} עוד לא נוצר. אפשר ליצור אותו במסך הדוחות.`,
    goToReports: 'למסך הדוחות',
    firstPage: 'עמוד ראשון',
    improved: 'טיפסו',
    published: 'פורסמו',
  },
  email: {
    title: 'סיכום שבועי במייל',
    description: 'תקציר קצר של הדירוגים והתוכן של הפרויקט, פעם בשבוע.',
    label: 'לשלוח לי סיכום שבועי',
    notLive: 'שליחת המיילים עוד לא הופעלה. ההעדפה נשמרת כבר עכשיו, ומיילים יתחילו לצאת רק אחרי שהשליחה תופעל.',
    on: 'פעיל',
    off: 'כבוי',
    saved: 'נשמר',
    failed: 'לא נשמר. נסו שוב.',
  },
}

export type MonthlyCopy = typeof he

const en: MonthlyCopy = {
  title: 'Monthly reports',
  subtitle: 'On the 1st of every month, a summary of the month that just ended appears here: rankings, content, AI visibility and Search Console. Nothing to set up.',
  monthsLabel: 'Months',
  loading: 'Loading your monthly reports…',
  loadError: 'We couldn’t load your monthly reports.',
  retry: 'Try again',
  firstTitle: (date) => `Your first monthly report arrives on ${date}`,
  firstBody: (month) => `It builds itself and sums up ${month}: which keywords climbed and which slipped, what went live, how AI engines mentioned you, and what’s lined up for the month after. Until then, the data keeps coming in.`,
  firstList: ['Keyword movement and your first-page count', 'Articles published', 'Mentions and citations in AI answers', 'Search Console clicks and impressions, if connected', 'What’s planned for next month'],
  missingTitle: (month) => `The ${month} report hasn’t been created`,
  missingBody: 'This happens when a project was opened mid-month or before monthly reports were switched on. You can create it now from the data already stored; once created, it doesn’t change.',
  missingAction: (month) => `Create the ${month} report`,
  insideTitle: 'What every report covers',
  insideBody: (date) => `From then on there’s nothing to click: the next report is created on its own on ${date}.`,
  missingFailed: 'We couldn’t create the report. Try again in a moment.',
  generateToast: { pending: 'Creating the report from the stored data. This takes a few seconds.', done: 'The report is ready and shown here.', failed: 'We couldn’t create the report. Try again in a moment.' },
  nextReport: (date) => `Next report: ${date}`,
  generatedAuto: (date) => `Created automatically on ${date}`,
  generatedOwner: (date) => `Created at your request on ${date}`,
  coversFrom: (date) => `The project was opened on ${date}, so the report starts from that day.`,
  copy: 'Copy summary',
  copied: 'Summary copied',
  download: 'Download the report',
  downloading: 'Preparing the file…',
  downloadFailed: 'We could not prepare the file. Please try again in a moment.',
  headlineParts: {
    firstPage: (n) => `${n} keywords on Google’s first page`,
    improved: (n) => `${n} climbed`,
    dropped: (n) => `${n} slipped`,
    published: (n) => `${n} articles published`,
    clicks: (n) => `${n} clicks from Google`,
    quiet: 'A quiet month: no ranking movement and no new content.',
  },
  tiles: {
    firstPage: 'On page one',
    firstPageSource: 'Our rank tracking · positions 1-10',
    wasAtStart: (n) => `At the start of the month: ${n}`,
    improved: 'Keywords that climbed',
    improvedSource: (steady) => `Unchanged: ${steady}`,
    published: 'Articles published',
    publishedSource: 'WordPress and Shopify, through the app',
    clicks: 'Clicks from Google',
    clicksSource: (from, to) => `${from} to ${to} · Search Console`,
    clicksMissing: 'No data',
    noChecks: 'Not checked this month',
    noKeywords: 'No keywords tracked',
  },
  improvedTitle: 'What climbed',
  droppedTitle: 'What slipped',
  movesSub: 'From the check before the month to its last check',
  outside: 'Outside 100',
  mapsTag: 'Maps',
  more: (n) => `and ${n} more`,
  noKeywords: 'No keywords are tracked yet, so there’s no movement to compare. Keywords you add will be in the next report.',
  noKeywordsAction: 'Add keywords',
  noChecks: 'Your keywords weren’t checked this month. Movement needs at least one rank check a month.',
  noChecksAction: 'Check rankings',
  noneImproved: (steady) => `No keyword climbed this month. ${steady} held their position.`,
  noneDropped: 'No keyword slipped this month.',
  singleCheck: 'Most keywords were checked only once, so there’s nothing to compare yet. Their movement shows here from next month.',
  publishedTitle: 'What went live',
  publishedNone: (month) => `No articles were published in ${month}. Every article published through the app counts in the month it went live.`,
  publishedAction: 'Open content strategy',
  channel: { wordpress: 'WordPress', shopify: 'Shopify', other: 'Published' },
  aiTitle: 'AI visibility',
  aiNone: 'No AI visibility checks ran this month. One check is enough for the next report to show how often you were mentioned and when you were cited as a source.',
  aiAction: 'Run a visibility check',
  aiAnswers: 'Answers checked',
  aiMentions: 'Mentioned you',
  aiCitations: 'Cited you as a source',
  gscTitle: 'Search Console',
  gscNotConnected: 'Search Console isn’t connected to this project, so there are no clicks or impressions here. Once connected, every report includes them.',
  gscConnect: 'Connect Search Console',
  gscNoData: 'Search Console is connected, but no sync covers this month. Syncs run weekly, and Google’s figures arrive about two days late.',
  gscClicks: 'Clicks',
  gscImpressions: 'Impressions',
  gscWindow: (from, to) => `28 days, ${from} to ${to}`,
  gscVsPrevious: (from, to) => `vs. ${from} to ${to}`,
  planTitle: (month) => `Planned for ${month}`,
  planSub: 'As the plan stood on the day this report was created',
  planScheduled: 'Scheduled to publish',
  planQueued: (n) => `${n} articles waiting in the automatic publishing queue`,
  planReady: (n) => `${n} articles written and ready to publish`,
  planApproved: 'Topics you approved for writing',
  planIdeas: 'Suggested ideas awaiting your call',
  planEmpty: 'There’s no content plan for next month yet. Your content strategy suggests topics from your keywords, and whatever you approve shows up here.',
  teaser: {
    title: 'Monthly report',
    open: 'Open the full report',
    firstBody: (date) => `Your first report is created on ${date} and covers the current month.`,
    missingBody: (month) => `The ${month} report hasn’t been created yet. You can create it on the Reports screen.`,
    goToReports: 'Go to Reports',
    firstPage: 'Page one',
    improved: 'Climbed',
    published: 'Published',
  },
  email: {
    title: 'Weekly email summary',
    description: 'A short digest of this project’s rankings and content, once a week.',
    label: 'Send me a weekly summary',
    notLive: 'Email sending isn’t switched on yet. Your preference is saved now, and emails will only start once sending goes live.',
    on: 'On',
    off: 'Off',
    saved: 'Saved',
    failed: 'Not saved. Try again.',
  },
}

const es: MonthlyCopy = {
  title: 'Informes mensuales',
  subtitle: 'El día 1 de cada mes aparece aquí un resumen del mes que acaba de terminar: posiciones, contenido, visibilidad en IA y Search Console. No hay nada que configurar.',
  monthsLabel: 'Meses',
  loading: 'Cargando tus informes mensuales…',
  loadError: 'No hemos podido cargar tus informes mensuales.',
  retry: 'Volver a intentarlo',
  firstTitle: (date) => `Tu primer informe mensual llega el ${date}`,
  firstBody: (month) => `Se construye solo y resume ${month}: qué palabras clave han subido y cuáles han bajado, qué se ha publicado, cómo te han mencionado los motores de IA y qué hay previsto para el mes siguiente. Hasta entonces, los datos siguen llegando.`,
  firstList: ['El movimiento de tus palabras clave y cuántas están en la primera página', 'Los artículos publicados', 'Menciones y citas en las respuestas de IA', 'Clics e impresiones de Search Console, si está conectado', 'Lo previsto para el mes que viene'],
  missingTitle: (month) => `El informe de ${month} no se ha creado`,
  missingBody: 'Esto pasa cuando un proyecto se abrió a mitad de mes o antes de activar los informes mensuales. Puedes crearlo ahora con los datos ya guardados; una vez creado, no cambia.',
  missingAction: (month) => `Crear el informe de ${month}`,
  insideTitle: 'Qué cubre cada informe',
  insideBody: (date) => `A partir de ahí no hay que hacer nada: el siguiente informe se crea solo el ${date}.`,
  missingFailed: 'No hemos podido crear el informe. Inténtalo dentro de un momento.',
  generateToast: { pending: 'Creando el informe con los datos guardados. Tarda unos segundos.', done: 'El informe está listo y se muestra aquí.', failed: 'No hemos podido crear el informe. Inténtalo dentro de un momento.' },
  nextReport: (date) => `Próximo informe: ${date}`,
  generatedAuto: (date) => `Creado automáticamente el ${date}`,
  generatedOwner: (date) => `Creado a petición tuya el ${date}`,
  coversFrom: (date) => `El proyecto se abrió el ${date}, así que el informe empieza ese día.`,
  copy: 'Copiar el resumen',
  copied: 'Resumen copiado',
  download: 'Descargar el informe',
  downloading: 'Preparando el archivo…',
  downloadFailed: 'No hemos podido preparar el archivo. Vuelve a intentarlo en un momento.',
  headlineParts: {
    firstPage: (n) => `${n} palabras clave en la primera página de Google`,
    improved: (n) => `${n} han subido`,
    dropped: (n) => `${n} han bajado`,
    published: (n) => `${n} artículos publicados`,
    clicks: (n) => `${n} clics desde Google`,
    quiet: 'Un mes tranquilo: sin movimiento de posiciones y sin contenido nuevo.',
  },
  tiles: {
    firstPage: 'En la primera página',
    firstPageSource: 'Nuestro seguimiento de posiciones · puestos 1-10',
    wasAtStart: (n) => `Al empezar el mes: ${n}`,
    improved: 'Palabras clave que han subido',
    improvedSource: (steady) => `Sin cambios: ${steady}`,
    published: 'Artículos publicados',
    publishedSource: 'WordPress y Shopify, desde la aplicación',
    clicks: 'Clics desde Google',
    clicksSource: (from, to) => `del ${from} al ${to} · Search Console`,
    clicksMissing: 'Sin datos',
    noChecks: 'Sin comprobaciones este mes',
    noKeywords: 'Sin palabras clave en seguimiento',
  },
  improvedTitle: 'Lo que ha subido',
  droppedTitle: 'Lo que ha bajado',
  movesSub: 'De la comprobación anterior al mes hasta su última comprobación',
  outside: 'Fuera del 100',
  mapsTag: 'Maps',
  more: (n) => `y ${n} más`,
  noKeywords: 'Todavía no hay palabras clave en seguimiento, así que no hay movimiento que comparar. Las que añadas estarán en el próximo informe.',
  noKeywordsAction: 'Añadir palabras clave',
  noChecks: 'Tus palabras clave no se han comprobado este mes. Para ver movimiento hace falta al menos una comprobación al mes.',
  noChecksAction: 'Comprobar posiciones',
  noneImproved: (steady) => `Ninguna palabra clave ha subido este mes. ${steady} han mantenido su posición.`,
  noneDropped: 'Ninguna palabra clave ha bajado este mes.',
  singleCheck: 'La mayoría de las palabras clave se han comprobado una sola vez, así que todavía no hay nada que comparar. Su movimiento aparece aquí a partir del mes que viene.',
  publishedTitle: 'Lo que se ha publicado',
  publishedNone: (month) => `No se publicó ningún artículo en ${month}. Cada artículo publicado desde la aplicación cuenta en el mes en que salió.`,
  publishedAction: 'Abrir la estrategia de contenidos',
  channel: { wordpress: 'WordPress', shopify: 'Shopify', other: 'Publicado' },
  aiTitle: 'Visibilidad en IA',
  aiNone: 'Este mes no se ha hecho ninguna comprobación de visibilidad en IA. Con una basta para que el próximo informe muestre cuántas veces te mencionaron y cuándo te citaron como fuente.',
  aiAction: 'Hacer una comprobación de visibilidad',
  aiAnswers: 'Respuestas comprobadas',
  aiMentions: 'Te han mencionado',
  aiCitations: 'Te han citado como fuente',
  gscTitle: 'Search Console',
  gscNotConnected: 'Search Console no está conectado a este proyecto, así que aquí no hay clics ni impresiones. En cuanto lo conectes, todos los informes los incluyen.',
  gscConnect: 'Conectar Search Console',
  gscNoData: 'Search Console está conectado, pero ninguna sincronización cubre este mes. Se sincroniza cada semana y las cifras de Google llegan con unos dos días de retraso.',
  gscClicks: 'Clics',
  gscImpressions: 'Impresiones',
  gscWindow: (from, to) => `28 días, del ${from} al ${to}`,
  gscVsPrevious: (from, to) => `frente al ${from} al ${to}`,
  planTitle: (month) => `Previsto para ${month}`,
  planSub: 'Tal como estaba el plan el día en que se creó este informe',
  planScheduled: 'Programado para publicarse',
  planQueued: (n) => `${n} artículos esperando en la cola de publicación automática`,
  planReady: (n) => `${n} artículos escritos y listos para publicar`,
  planApproved: 'Temas que has aprobado para escribir',
  planIdeas: 'Ideas propuestas pendientes de tu decisión',
  planEmpty: 'Todavía no hay plan de contenidos para el mes que viene. Tu estrategia de contenidos propone temas a partir de tus palabras clave, y lo que apruebes aparece aquí.',
  teaser: {
    title: 'Informe mensual',
    open: 'Abrir el informe completo',
    firstBody: (date) => `Tu primer informe se crea el ${date} y cubre el mes en curso.`,
    missingBody: (month) => `El informe de ${month} todavía no se ha creado. Puedes crearlo en la pantalla de Informes.`,
    goToReports: 'Ir a Informes',
    firstPage: 'Primera página',
    improved: 'Han subido',
    published: 'Publicados',
  },
  email: {
    title: 'Resumen semanal por correo',
    description: 'Un resumen breve de las posiciones y el contenido de este proyecto, una vez por semana.',
    label: 'Enviarme un resumen semanal',
    notLive: 'El envío de correos todavía no está activado. Tu preferencia se guarda ahora, y los correos solo empezarán cuando el envío esté en marcha.',
    on: 'Activado',
    off: 'Desactivado',
    saved: 'Guardado',
    failed: 'No se ha guardado. Inténtalo otra vez.',
  },
}

export function monthlyCopy(l: PublicLocale): MonthlyCopy {
  return l === 'he' ? he : l === 'es' ? es : en
}
