/**
 * The article-design step of generation: the images a new article gets, by
 * the project's settings. Called ONCE, from generateArticleForTopic
 * (lib/content/article-generation.ts), right after the draft is stored, in
 * place of the old "auto featured image" block, which it keeps exactly:
 *
 *   - the hero: made as before (deps.createFeaturedImage), in the project's
 *     image style and hero shape (read by createFeaturedImageForArticle), and
 *     still switched off by CONTENT_AUTO_FEATURED_IMAGE=false;
 *   - NEW, inline images: when the project asks for N (1 to 4), N rows in
 *     article_inline_images at N section breaks spread through the article,
 *     each generated by the existing inline-image generator (same provider,
 *     same entitlement gate, same storage), in the same style;
 *   - "own images only": neither is made; the owner adds their site's images.
 *
 * The hero and the inline images are made at the same time, so the step takes
 * about as long as the hero alone did. Best-effort throughout: an image that
 * fails is a 'failed' row the owner can regenerate in the editor, never a
 * failed generation. With no settings (or no table yet) this is exactly the
 * old block: the hero, no inline images.
 *
 * The design of the body (formatted or minimal) is NOT baked in here: it is
 * composed when the article is shown or published (./html.ts), so the stored
 * body stays the plain HTML every other tool reads.
 */
import type { SupabaseClient } from '@supabase/supabase-js'
import { eligibleSections } from '@/lib/content/inline-images-compose'
import { generateInlineImage } from '@/lib/content/inline-images'
import { projectOwner, readProjectArticleStyle } from './store'
import type { ArticleStyle } from './types'

type FeaturedResult = { featured_image_url: string } | { error: string }
type InlineResult = { ok: true; url: string } | { ok: false; error: string; transient?: boolean }

export type ArticleImageStepDeps = {
  /** The existing hero generator, bound to this article. */
  createFeaturedImage: () => Promise<FeaturedResult>
  /** The existing inline-image generator; injectable for tests. */
  generateInline?: (admin: SupabaseClient, imageId: string) => Promise<InlineResult>
  env?: Record<string, string | undefined>
}

export type ArticleImageStepResult = {
  imageGenerated: boolean
  style: ArticleStyle
  inline: { requested: number; created: number; ready: number }
}

/** `n` sections spread evenly through the article (first, last and between), never two the same. */
export function spreadSections<T>(sections: readonly T[], n: number): T[] {
  if (n <= 0 || !sections.length) return []
  if (n >= sections.length) return [...sections]
  if (n === 1) return [sections[Math.floor((sections.length - 1) / 2)] as T]
  const picked: T[] = []
  for (let i = 0; i < n; i++) picked.push(sections[Math.round((i * (sections.length - 1)) / (n - 1))] as T)
  return picked
}

const stripTags = (s: string) => s.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()

/** What the section is about, for the image: its heading and the start of its first paragraph. */
function sectionBrief(html: string, sectionId: string, title: string): string {
  const esc = sectionId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const m = html.match(new RegExp(`<h2\\b[^>]*\\bid="${esc}"[^>]*>[\\s\\S]*?<\\/h2>\\s*<p\\b[^>]*>([\\s\\S]*?)<\\/p>`, 'i'))
  const para = m ? stripTags(m[1] ?? '').slice(0, 220) : ''
  return [title, para].filter(Boolean).join(' — ')
}

async function createInlineImages(
  admin: SupabaseClient,
  ids: { articleId: string; projectId: string; ownerId: string },
  count: number,
  generate: (admin: SupabaseClient, imageId: string) => Promise<InlineResult>,
): Promise<{ created: number; ready: number }> {
  const { data: art } = await admin.from('generated_articles').select('content_html').eq('id', ids.articleId).eq('project_id', ids.projectId).maybeSingle()
  const html = String((art as { content_html?: string | null } | null)?.content_html ?? '')
  const targets = spreadSections(eligibleSections(html), count)
  if (!targets.length) return { created: 0, ready: 0 }

  const now = new Date().toISOString()
  const { data: rows, error } = await admin.from('article_inline_images').insert(targets.map((s, position) => ({
    user_id: ids.ownerId,
    project_id: ids.projectId,
    article_id: ids.articleId,
    section_id: s.sectionId,
    prompt: sectionBrief(html, s.sectionId, s.title),
    alt_text: s.title.slice(0, 200),
    caption: null,
    position,
    status: 'pending',
    updated_at: now,
  }))).select('id')
  if (error || !Array.isArray(rows)) {
    console.warn('[article-style] inline image rows skipped', { code: (error as { code?: string } | null)?.code ?? 'no_rows' })
    return { created: 0, ready: 0 }
  }
  const results = await Promise.all((rows as { id: string }[]).map((r) =>
    generate(admin, r.id).catch((): InlineResult => ({ ok: false, error: 'unexpected_error' }))))
  return { created: rows.length, ready: results.filter((r) => r.ok).length }
}

export async function runArticleImageStep(
  admin: SupabaseClient,
  ids: { articleId: string; projectId: string; ownerId: string },
  deps: ArticleImageStepDeps,
): Promise<ArticleImageStepResult> {
  const env = deps.env ?? process.env
  // The settings row is the project owner's: read with the owner the project row names.
  const owner = (await projectOwner(admin, ids.projectId)) ?? ids.ownerId
  ids = { ...ids, ownerId: owner }
  const { style } = await readProjectArticleStyle(admin, ids.projectId, owner)
  const makeImages = !style.ownImagesOnly

  const hero = (async () => {
    if (!makeImages || env.CONTENT_AUTO_FEATURED_IMAGE === 'false') return false
    try {
      const img = await deps.createFeaturedImage()
      if ('error' in img) console.warn('[content-article-generation] auto image skipped', { articleId: ids.articleId, reason: img.error })
      return !('error' in img)
    } catch (e) {
      console.warn('[content-article-generation] auto image threw', { message: e instanceof Error ? e.message : String(e) })
      return false
    }
  })()

  const requested = makeImages ? style.inlineImages : 0
  const inline = (async () => {
    if (requested <= 0) return { created: 0, ready: 0 }
    try {
      const generate = deps.generateInline ?? ((a: SupabaseClient, id: string) => generateInlineImage(a as never, id))
      return await createInlineImages(admin, ids, requested, generate)
    } catch (e) {
      console.warn('[article-style] inline images threw', { message: e instanceof Error ? e.message : String(e) })
      return { created: 0, ready: 0 }
    }
  })()

  const [imageGenerated, made] = await Promise.all([hero, inline])
  if (requested > 0) console.log('[article-style] inline images', { articleId: ids.articleId, requested, ...made })
  return { imageGenerated, style, inline: { requested, ...made } }
}
